add colors to git hooks

diff --git a/git/git_template/hooks/pre-push b/git/git_template/hooks/pre-push
--- a/git/git_template/hooks/pre-push
+++ b/git/git_template/hooks/pre-push
@@ -23,6 +23,10 @@
 # remote="$1"
 # url="$2"
 
+# Colors
+RED='\033[0;31m'
+NO_COLOR='\033[0m'
+
 zero=$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')
 
 # shellcheck disable=SC2034
@@ -46,7 +50,7 @@ do
 		commit=$(git rev-list -n 1 --grep '^WIP' "$range")
 		if test -n "$commit"
 		then
-			echo >&2 "Found WIP commit in $local_ref, not pushing"
+			echo >&2 "${RED}Error:${NO_COLOR} Found WIP commit in $local_ref, not pushing"
 			exit 1
 		fi
 	fi
@@ -56,7 +60,7 @@ done
 # Adapted from https://github.com/zricethezav/gitleaks/wiki/Scanning
 gitleaks detect --verbose --redact
 if [[ ${PIPESTATUS[0]} -gt 0 ]]; then
-    echo "Error: gitleaks has detected sensitive information in your changes."
+    echo "${RED}Error:${NO_COLOR} gitleaks has detected sensitive information in your changes."
     exit 1
 fi
 
